#!/bin/bash -e

if [ "$#" -lt 2 ] || ["$#" -ge 4];
  then echo "Usage: stats {-rows|-cols} [file]" >&2
  #send to stderr
  exit
fi

rowCol=$2

if [[${rowCol:0:1} == "c"]]
  then #call statistics func

elif [[${rowCol:0:1} == "r"]]
  then calc_avg #call statistics func

else
  echo "Invalid commandline arguments." >&2
  #send to stderr
  exit
fi


calc_avg(){

  echo "Median Mean"
  while read line #reads from stdin if no file
  do
    #median
    #echo "$line"
    count_num = wc $line
    firstHalf = expr $count_num / 2

    if[[ $count_num % 2 -gt 0 ]]
      then expr $firstHalf + 1
    fi

    secondHalf = $count_num - $firstHalf
    $line | tr '\t' '\n' | sort -n | head -n $firstHalf > file1.txt | tail -n $secondHalf > file2.txt #
    if[[ $count_num % 2 == 0 ]]
      if [[tail -n 1 $file1 -gt head -n 1 $file2]]
      then
        median = tail -n 1 $file1
      else
        median = head -n 1 $file2
      fi
    else
      median = tail -n 1 file1.txt
    fi
    printf "$median \t"
    #average

    for char in $line; do
      sum = expr $char + $sum

    mean = expr $sum/$count
    printf "$mean"





  done < "${1:-/dev/stdin}"
}
exit 0 #exit with no errors
